services:
  postgres:
    image: postgres:16
    container_name: estoque-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: estoque_operacional
      POSTGRES_USER: estoque_user
      POSTGRES_PASSWORD: estoque_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

