services:
  - type: web
    name: estoque-operacional-api
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install && npm run prisma:deploy && npm run seed && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URLS
        sync: false
      - key: COOKIE_SECURE
        value: "true"
      - key: COOKIE_SAME_SITE
        value: none

  - type: static_site
    name: estoque-operacional-web
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
